[package]
name = "forksrv"
version = "0.1.0"
authors = ["coco <coco@hexgolems.com>", "daniel daniel.teuchert@rub.de"]
edition = "2024"

[dependencies]
nix = { version = "0.31", features = ["fs", "process", "signal"] }
libc = "0.2"
tempfile = "3.27"
serde_derive = "1.0"
serde = { version = "1.0", features = ["derive"] }
byteorder = "1.5"
snafu = "0.9"
timeout-readwrite = "0.4"
